name = "sgdodigi" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "sg1.gyz.my.id"
custom_domain = true
[[routes]]
pattern = "cvs-deo.shopeemobile.com.sg1.gyz.my.id"
custom_domain = true
[[routes]]
pattern = "cf.shopee.co.id.sg1.gyz.my.id"
custom_domain = true
[[routes]]
pattern = "cv.shopee.sg1.gyz.my.id"
custom_domain = true
[[routes]]
pattern = "cvs-deo.shopeemobile.com.sg1.gyz.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.sgdo.gyzeira.biz.id"
custom_domain = true
[[routes]]
pattern = "dl-cvs.ggbluefox.com.sg1.gyz.my.id"
custom_domain = true
[[routes]]
pattern = "img.email1.vidio.com.sg1.gyz.my.id"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "5bbba812-32d3-4fe7-9abb-b81a9f0659aa"
