name = "ID-GYZ" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "id.gyzeira.biz.id"
custom_domain = true
[[routes]]
pattern = "shopee.co.id.id.gyzeira.biz.id"
custom_domain = true
[[routes]]
pattern = "cf.shopee.co.id.id.gyzeira.biz.id"
custom_domain = true
[[routes]]
pattern = "cv.shopee.sg.id.gyzeira.biz.id"
custom_domain = true
[[routes]]
pattern = "cvs-deo.shopeemobile.com.id.gyzeira.biz.id"
custom_domain = true
[[routes]]
pattern = "dl-cvs.ggbluefox.com.id.gyzeira.biz.id"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "43f1f9dd-4d21-4174-af7f-d57f82674402"
